export default [
  {
    url: '/home',
    name: "Home",
    i18n: "Home",
    slug: "home",
    icon: "HomeIcon",
  },
  {
    header: "Estatísticas",
    i18n: "Estatísticas",
    items: [
      {
        url: null,
        name: "Relatórios",
        i18n: "Relatórios",
        slug: "relatorios",
        icon: "FileTextIcon",
        submenu: [
          {
            url: null,
            name: "Log",
            i18n: "Log",
            slug: "log",
            icon: "FileTextIcon",
            submenu: [
              {
                url: '/relatorio/msglog',
                name: "Msg X Log",
                i18n: "Msg X Log",
                slug: "msgLog",
                icon: "MessageSquareIcon",
              },
              {
                url: '/relatorio/integralog',
                name: "Integra X Log",
                i18n: "Integra X Log",
                slug: "log",
                icon: "FileTextIcon",
              },
              {
                url: '/relatorio/integralogretorno',
                name: "Integra Retorno X Log",
                i18n: "Integra Retorno X Log",
                slug: "log",
                icon: "FileTextIcon",
              },
              {
                url: '/relatorio/integrapallet',
                name: "Integra X Pallets",
                i18n: "Integra X Pallets",
                slug: "integra",
                icon: "LayersIcon",
              },
            ]
          },
          {
            url: null,
            name: "Produção",
            i18n: "Produção",
            slug: "producao",
            icon: "FileTextIcon",
            submenu: [
              {
                url: '/relatorio/prodperiodo',
                name: "Prod X Período",
                i18n: "Prod X Período",
                slug: "prodperiodo",
                icon: "CalendarIcon",
              },
              {
                url: '/relatorio/prodrampa',
                name: "Prod X Rampa",
                i18n: "Prod X Rampa",
                slug: "prodrampa",
                icon: "ArrowUpRightIcon",
              },
              {
                url: '/relatorio/volumependenterampa',
                name: "Volumes Pendentes por Rampa",
                i18n: "Volumes Pendentes por Rampa",
                slug: "volumependenterampa",
                icon: "AlertCircleIcon",
              },
              {
                url: '/relatorio/prodvolume',
                name: "Prod X Volume",
                i18n: "Prod X Volume",
                slug: "prodvolume",
                icon: "CodepenIcon",
              },
              {
                url: '/relatorio/prodoperador',
                name: "Prod X Operador",
                i18n: "Prod X Operador",
                slug: "prodoperador",
                icon: "BoxIcon",
              },
              {
                url: '/relatorio/palletsoperador',
                name: "Pallets X Operador",
                i18n: "Pallets X Operador",
                slug: "prodpallets",
                icon: "ActivityIcon",
              },
              {
                url: '/relatorio/volumehora',
                name: "Volume X Hora",
                i18n: "Volume X Hora",
                slug: "prodvolume",
                icon: "ClockIcon",
              },
              {
                url: '/relatorio/ociosidade',
                name: "Tempo Ocioso",
                i18n: "Tempo Ocioso",
                slug: "ociosidade",
                icon: "AlertCircleIcon",
              },
              {
                url: '/relatorio/rampacheia',
                name: "Rampa Cheia",
                i18n: "Rampa Cheia",
                slug: "rampacheia",
                icon: "AlertTriangleIcon",
              },
              {
                url: '/relatorio/prodfaltaleitura',
                name: "Produto Desviado sem Pallet",
                i18n: "Produto Desviado sem Pallet",
                slug: "prodfaltaleitura",
                icon: "ClockIcon",
              },
              {
                url: '/relatorio/prodposto',
                name: "Prod X Posto",
                i18n: "Prod X Posto",
                slug: "prodposto",
                icon: "ArrowUpRightIcon",
              },
              {
                url: '/relatorio/prodtipoproduto',
                name: "Prod X Familia Produto",
                i18n: "Prod X Familia Produto",
                slug: "prodtipoproduto",
                icon: "ArrowUpRightIcon",
              },
              {
                url: '/relatorio/prodpickingproduto',
                name: "Prod X Picking Produto",
                i18n: "Prod X Picking Produto",
                slug: "prodpickingproduto",
                icon: "ArrowUpRightIcon",
              },
              {
                url: '/relatorio/prodconferencia',
                name: "Prod X Conferência",
                i18n: "Prod X Conferência",
                slug: "prodconferencia",
                icon: "CodepenIcon",
              },
              {
                url: '/relatorio/prodvolumeonda',
                name: "Volume X Onda",
                i18n: "Volume X Onda",
                slug: "prodvolumeonda",
                icon: "CodepenIcon",
              },

            ]
          },
          {
            url: null,
            name: "Rota",
            i18n: "Rota",
            slug: "rota",
            icon: "FileTextIcon",
            submenu: [
              {
                url: '/relatorio/ramparota',
                name: "Rampa X Rota",
                i18n: "Rampa X Rota",
                slug: "rotarampa",
                icon: "ShoppingCartIcon",
              },
              {
                url: '/relatorio/pickingrota',
                name: "Picking X Rota",
                i18n: "Picking X Rota",
                slug: "rotapicking",
                icon: "SlidersIcon",
              },
            ]
          },
          {
            url: null,
            name: "Acesso",
            i18n: "Acesso",
            slug: "acesso",
            icon: "FileTextIcon",
            submenu: [
              {
                url: '/relatorio/acessousuario',
                name: "Acesso X Usuário",
                i18n: "Acesso X Usuário",
                slug: "acessousuario",
                icon: "KeyIcon",
              },
            ]
          },
          {
            url: null,
            name: "Produtos",
            i18n: "Produtos",
            slug: "produtos",
            icon: "FileTextIcon",
            submenu: [
              {
                url: '/relatorio/produtopicking',
                name: "Produtos X Posição",
                i18n: "Produtos X Posição",
                slug: "produtopicking",
                icon: "KeyIcon",
              },
            ]
          },
        ]
      },
      {
        url: null,
        name: "Dashboards",
        i18n: "Dashboards",
        slug: "dashboards",
        icon: "PieChartIcon",
        submenu: [
          {
            url: '/dashboard/pdireito',
            name: "Painel Direito",
            i18n: "Painel Direito",
            slug: "pdireito",
            icon: "YoutubeIcon",
          },
          {
            url: '/dashboard/pesquerdo',
            name: "Painel Esquerdo",
            i18n: "Painel Esquerdo",
            slug: "pesquerdo",
            icon: "YoutubeIcon",
          },
          {
            url: '/dashboard/pdireitosorter',
            name: "Painel Dir. Sorter",
            i18n: "Painel Dir. Sorter",
            slug: "pdireitosorter",
            icon: "YoutubeIcon",
          },
          {
            url: '/dashboard/pesquerdosorter',
            name: "Painel Esq. Sorter",
            i18n: "Painel Esq. Sorter",
            slug: "pesquerdosorter",
            icon: "YoutubeIcon",
          },

        ]
      }
    ]
  },
  {
    header: "Interface",
    i18n: "Interface",
    items: [
      {
        url: null,
        name: "Operação",
        i18n: "Operação",
        slug: "operacao",
        icon: "PowerIcon",
        submenu: [
          {
            url: "/interface/operacao/onda",
            name: "Onda",
            i18n: "Onda",
            slug: "onda",
            icon: "PlayIcon",
          },
          {
            url: "/interface/operacao/opMapaSorter",
            name: "Mapa Sorter",
            i18n: "Mapa Sorter",
            slug: "mapasorter",
            icon: "PlayIcon",
          },
          {
            url: "/interface/operacao/opMapaPtl",
            name: "Mapa Ptl",
            i18n: "Mapa Ptl",
            slug: "mapaptl",
            icon: "PlayIcon",
          },
					{
						url: "/interface/operacao/opMapaPtm",
						name: "Mapa Contingência",
						i18n: "Mapa Contingência",
	//					name: "Mapa Ptm",
//						i18n: "Mapa Ptm",
						slug: "mapaptm",
						icon: "PlayIcon",
					},
          {
            url: "/interface/operacao/oprevisapallet",
            name: "Revisa Pallets",
            i18n: "Revisa Pallets",
            slug: "revisapallet",
            icon: "EditIcon",
          },
          {
            url: "/interface/operacao/oprejeitados",
            name: "Rejeitados",
            i18n: "Rejeitados",
            slug: "rejeitados",
            icon: "AlertTriangleIcon",
          },
          {
            url: "/interface/operacao/opexcecao",
            name: "Volume Exceção",
            i18n: "Volume Exceção",
            slug: "rejeitados",
            icon: "CastIcon",
          },
          {
            url: "/interface/operacao/opReprocessaOnda",
            name: "Reprocessar Onda",
            i18n: "Reprocessar Onda",
            slug: "reprocessa",
            icon: "CastIcon",
          },
          {
            url: "/interface/operacao/opOrderStart",
            name: "Order Start",
            i18n: "Order Start",
            slug: "orderstart",
            icon: "CastIcon",
          },
          {
            url: "/interface/operacao/opConferencia",
            name: "Conferência",
            i18n: "Conferência",
            slug: "conferencia",
            icon: "AlertTriangleIcon",
          },
					{
						url: "/interface/operacao/opPTM",
						name: "Contingência",
						i18n: "Contingência",
	//					name: "PTM",
//						i18n: "PTM",
						slug: "PTM",
						icon: "AlertTriangleIcon",
					},

        ],
      },
      {
        url: null,
        name: "Rotas",
        i18n: "Rotas",
        slug: "rotas",
        icon: "TruckIcon",
        submenu: [
          {
            url: "/interface/rota/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/interface/rota/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },
      {
        url: null,
        name: "Sorters",
        i18n: "Sorters",
        slug: "sorters",
        icon: "MapPinIcon",
        submenu: [
          {
            url: "/interface/sorter/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/interface/sorter/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
          {
            url: null,
            name: "Mapas Sorters",
            i18n: "Mapas Sorters",
            slug: "mapassorters",
            icon: "MapIcon",
            submenu: [
              {
                url: "/interface/mapaSorter/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/interface/mapaSorter/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
            ],
          },
          {
            url: null,
            name: "Rampas",
            i18n: "Rampas",
            slug: "rampas",
            icon: "PackageIcon",
            submenu: [
              {
                url: "/interface/rampa/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/interface/rampa/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
              {
                url: null,
                name: "Coletores",
                i18n: "Coletores",
                slug: "coletores",
                icon: "RssIcon",
                submenu: [
                  {
                    url: "/interface/coletor/consulta",
                    name: "Consulta",
                    i18n: "Consulta",
                    slug: "consulta",
                    icon: "SearchIcon",
                  },
                  {
                    url: "/interface/coletor/cadastro",
                    name: "Cadastro",
                    i18n: "Cadastro",
                    slug: "cadastro",
                    icon: "FilePlusIcon",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        url: null,
        name: "PTLs",
        i18n: "PTLs",
        slug: "ptls",
        icon: "SendIcon",
        submenu: [
          {
            url: "/interface/ptl/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/interface/ptl/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
          {
            url: "/interface/ptl/impressao",
            name: "Impressão",
            i18n: "Impressão",
            slug: "Impressão",
            icon: "PrinterIcon",
          },
          {
            url: null,
            name: "Mapas PTLs",
            i18n: "Mapas PTLs",
            slug: "mapasptls",
            icon: "GlobeIcon",
            submenu: [
              {
                url: "/interface/mapaPtl/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/interface/mapaPtl/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
            ],
          },
        ],
      },
			{
				url: null,
				name: "Contingência",
				i18n: "Contingência",
	//			name: "PTM",
//				i18n: "PTM",
				slug: "PTM",
				icon: "SendIcon",
				submenu: [
					{
						url: "/interface/ptm/consulta",
						name: "Consulta",
						i18n: "Consulta",
						slug: "consulta",
						icon: "SearchIcon",
					},
					{
						url: "/interface/ptm/cadastro",
						name: "Cadastro",
						i18n: "Cadastro",
						slug: "cadastro",
						icon: "FilePlusIcon",
					},
					{
						url: null,
						name: "Mapas Contingência",
						i18n: "Mapas Contingência",
	//					name: "Mapas PTM",
//						i18n: "Mapas PTM",
						slug: "mapasptm",
						icon: "GlobeIcon",
						submenu: [
							{
								url: "/interface/mapaPtm/consulta",
								name: "Consulta",
								i18n: "Consulta",
								slug: "consulta",
								icon: "SearchIcon",
							},
							{
								url: "/interface/mapaPtm/cadastro",
								name: "Cadastro",
								i18n: "Cadastro",
								slug: "cadastro",
								icon: "FilePlusIcon",
							},
						],
					},
				],
			},
			{
				url: "/interface/reimprimiretiqueta",
				name: "Reimprimir Etiqueta",
				i18n: "Reimprimir Etiqueta",
				slug: "reimprimir-etiqueta",
				icon: "PrinterIcon",
			},

    ]
  },

  {
    header: "Cadastros",
    i18n: "Cadastros",
    items: [
      {
        url: null,
        name: "Caixas",
        i18n: "Caixas",
        slug: "caixas",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/caixas/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/caixas/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },

      {
        url: null,
        name: "Transportadoras",
        i18n: "Transportadoras",
        slug: "transportadoras",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/transportadora/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/transportadora/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },

      {
        url: null,
        name: "Postos",
        i18n: "Postos",
        slug: "Postos",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/postos/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/postos/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },

      {
        url: null,
        name: "Ponto de Decisão",
        i18n: "Ponto de Decisão",
        slug: "Ponto de Decisão",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/pontoDecisao/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/pontoDecisao/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },


      {
        url: null,
        name: "Produtos",
        i18n: "Produtos",
        slug: "Produtos",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/produtos/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/produtos/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
          {
            url: "/interface/importaprodutos",
            name: "Importar Produtos",
            i18n: "Importar Produtos",
            slug: "importaprodutos",
            icon: "UploadIcon",
          },
          {
            url: null,
            name: "Tipo Produto",
            i18n: "tipoproduto",
            slug: "tipoproduto",
            icon: "UserPlusIcon",
            submenu: [
              {
                url: "/cadastros/produtos/tipoproduto/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/cadastros/produtos/tipoproduto/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
            ],
          },

        ],
      },

      {
        url: null,
        name: "Endereços",
        i18n: "Endereços",
        slug: "Endereços",
        icon: "RadioIcon",
        submenu: [
          {
            url: "/interface/picking/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/interface/picking/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },
			{
				url: null,
				name: "Endereços Contingência",
				i18n: "Endereços Contingência",
	//			name: "Endereços PTM",
//				i18n: "Endereços PTM",
				slug: "Endereços PTM",
				icon: "RadioIcon",
				submenu: [
					{
						url: "/interface/enderecoPtm/consulta",
						name: "Consulta",
						i18n: "Consulta",
						slug: "consulta",
						icon: "SearchIcon",
					},
					{
						url: "/interface/enderecoPtm/cadastro",
						name: "Cadastro",
						i18n: "Cadastro",
						slug: "cadastro",
						icon: "FilePlusIcon",
					},
				],
			},

      {
        url: null,
        name: "Gateways",
        i18n: "Gateways",
        slug: "gateways",
        icon: "CloudIcon",
        submenu: [
          {
            url: "/interface/gateway/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/interface/gateway/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },

      {
        url: null,
        name: "Franqueados",
        i18n: "Franqueados",
        slug: "Franqueados",
        icon: "BoxIcon",
        submenu: [
          {
            url: "/cadastros/franqueado/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/cadastros/franqueado/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },



    ]
  },

  {
    header: "Administração",
    i18n: "Administração",
    items: [
      {
        url: null,
        name: "Usuários",
        i18n: "Usuários",
        slug: "usuario",
        icon: "UserIcon",
        submenu: [
          {
            url: "/adm/usuario/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/adm/usuario/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
          {
            url: null,
            name: "Função",
            i18n: "Função",
            slug: "funcao",
            icon: "UserPlusIcon",
            submenu: [
              {
                url: "/adm/usuario/funcao/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/adm/usuario/funcao/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
            ],
          },
        ],
      },
      {
        url: null,
        name: "Grupos",
        i18n: "Grupos",
        slug: "grupos",
        icon: "UsersIcon",
        submenu: [
          {
            url: "/adm/grupo/consulta",
            name: "Consulta",
            i18n: "Consulta",
            slug: "consulta",
            icon: "SearchIcon",
          },
          {
            url: "/adm/grupo/cadastro",
            name: "Cadastro",
            i18n: "Cadastro",
            slug: "cadastro",
            icon: "FilePlusIcon",
          },
        ],
      },
      {
        url: null,
        name: "Sistema",
        i18n: "Sistema",
        slug: "sistema",
        icon: "AirplayIcon",
        submenu: [
          {
            url: "/adm/sistema/integracao/cadastro",
            name: "Integrações",
            i18n: "Integrações",
            slug: "Integracoes",
            icon: "DatabaseIcon",
          },
          {
            url: "/adm/sistema/servico/cadastro",
            name: "Serviços",
            i18n: "Serviços",
            slug: "Servicos",
            icon: "PlayCircleIcon",
          },
          {
            url: "/adm/sistema/config/",
            name: "Configurações",
            i18n: "Configurações",
            slug: "configuracoes",
            icon: "SettingsIcon",
          },
          {
            url: "/adm/sistema/limparPostos",
            name: "Limpar Postos",
            i18n: "Limpar Postos",
            slug: "limparPostos",
            icon: "EditIcon",
          },
          {
            url: null,
            name: "Acessos",
            i18n: "Acessos",
            slug: "acessos",
            icon: "LogInIcon",
            submenu: [
              {
                url: "/adm/sistema/acesso/consulta",
                name: "Consulta",
                i18n: "Consulta",
                slug: "consulta",
                icon: "SearchIcon",
              },
              {
                url: "/adm/sistema/acesso/cadastro",
                name: "Cadastro",
                i18n: "Cadastro",
                slug: "cadastro",
                icon: "FilePlusIcon",
              },
            ],
          },
        ],
      },
      {
        url: null,
        name: "",
        i18n: "",
        slug: "",
        icon: "",
      },
      {
        url: null,
        name: "",
        i18n: "",
        slug: "",
        icon: "",
      },
      {
        url: null,
        name: "",
        i18n: "",
        slug: "",
        icon: "",
      },
    ]
  },
]
